build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.4
  amd64: ghcr.io/hassio-addons/base:17.2.4
  armv7: ghcr.io/hassio-addons/base:17.2.4
args:
  CHIRPSTACK_VERSION: 4.11.1
  CHIRPSTACK_GATEWAY_BRIDGE_VERSION: 4.0.11
  CHIRPSTACK_REST_API_VERSION: 4.10.2

#cosign:
#  identity: https://github.com/home-assistant/docker-base/.*
#labels:
#  io.hass.base.name: alpine
#  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
