build_from:
  aarch64: ghcr.io/hassio-addons/base:17.1.0
  amd64: ghcr.io/hassio-addons/base:17.1.0
  armv7: ghcr.io/hassio-addons/base:17.1.0
args:
  CHIRPSTACK_VERSION: 4.11.1
  CHIRPSTACK_GATEWAY_BRIDGE_VERSION: 4.0.11

#cosign:
#  identity: https://github.com/home-assistant/docker-base/.*
#labels:
#  io.hass.base.name: alpine
#  org.opencontainers.image.source: https://github.com/home-assistant/docker-base
