# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Chirp2MQTT
version: "1.1.128"
slug: chirp2mqtt
description: HA add-on to incorporatex ChirpStack LoraWan devices into MQTT integration
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
url: "https://github.com/modrisb/chirpha"
startup: application
webui: http://[HOST]:[PORT:8080]
boot: auto
ports:
  8080/tcp: 8080
  1700/udp: 1700
ports_description:
  8080/tcp: "ChirpStack server WEB UI port"
  1700/udp: "Port to receive LoraWAN packets"
homeassistant: "2024.3.1"
map:
  - homeassistant_config
  - addon_config
  - addons
  - share:rw
init: false
options:
  application_id: ""
  mqtt_user: "loramqtt"
  mqtt_password: "ploramqtt"
  discovery_prefix: "homeassistant"
  options_start_delay: 2
  options_restore_age: 4
  options_online_per_device: 0
  options_add_expire_after: false
  options_log_level: "info"
  database_actions: "None"
schema:
  application_id: "str"
  mqtt_user: "str"
  mqtt_password: "str?"
  discovery_prefix: "str"
  options_start_delay: "int(0,)"
  options_restore_age: "int(0,)"
  options_online_per_device: "float(0,)"
  options_add_expire_after: "bool"
  options_log_level: "list(detail|debug|info|warning|error|fatal|critical)?"
  database_actions: "list(None|Backup|Restore|Backup and restore)?"
timeout: 10
services:
  - mqtt:need
stage: experimental
